# Generated by Django 3.1.6 on 2021-09-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.rider')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
