# Generated by Django 3.1.6 on 2021-09-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='station',
            new_name='station_id',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='user',
            new_name='user_id',
        ),
    ]
